### PR TITLE
[PPN-68263] Add credit refund method to orbital

### PR DESCRIPTION
**Pull request by priceline-scottini**

### CODE REVIEW

**Review by dgknght — APPROVED** [review]

**Comment by cgriego** [comment]
@priceline-scottini @dgknght This isn't an appropriate change to make to the public project.

**Comment by dgknght** [comment]
> @priceline-scottini @dgknght This isn't an appropriate change to make to the public project.

Ah...sorry, I wasn't paying close enough attention to the project that contains the change. I was thinking we'd monkey-path (duck-punch) the class in our own project.

**Comment by dgknght** [comment]
We need to address customizations specific to our projects outside of this project.

**Comment by cgriego** [comment]
FYI it looks like upstream has a credit method. https://github.com/activemerchant/active_merchant/blob/853b91e0cde11495cdb42fec6839e574dc43ef1c/lib/active_merchant/billing/gateways/orbital.rb#L252-L258

**Pull request closed without merging**
